main/library/urls.py
from django.urls import path
from .views import IndexView, BookListView, basket_add, basket_remove


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('catalog/', BookListView.as_view(), name='catalog'),
    path('page/<int:page>/', BookListView.as_view(), name='paginator'),
    path('baskets/add/<int:book_id>/', basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
    path('author/<int:author_id>/', BookListView.as_view(), name='author')
]

main/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('', include(('library.urls', 'library'),  namespace='books')),
    path('users/', include(('users.urls', 'users'), namespace='users'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import UserLoginView, UserRegistrationView, ProfileUserView


urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('profile/<int:pk>', login_required(ProfileUserView.as_view()), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout')
]

main/library/models.py
from django.db import models
from django.utils.timezone import now



class Author(models.Model):
    name = models.CharField(
        max_length=128,
        blank=False,
        null=False,
        unique=True,
        verbose_name='Автор'
    )

    slug = models.SlugField(
        max_length=128,
        blank=False,
        null=False,
        unique=True,
        verbose_name='URL'
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'автор',
        verbose_name_plural = 'авторы'

class Book(models.Model):
    title = models.CharField(
        max_length=258,
        blank=False,
        null=False,
        unique=True,
        verbose_name='Книга'
    )

    slug = models.SlugField(
        max_length=258,
        blank=False,
        null=False,
        unique=True,
        verbose_name='URL'
    )

    quantity = models.PositiveIntegerField(
        default=1,
        blank=False,
        null=False,
        verbose_name='количество экземпляров'
    )

    author = models.ForeignKey(
        to='Author',
        on_delete=models.CASCADE
    )

    image = models.ImageField(
        upload_to='book_images',
        blank=False,
        null=False,
        verbose_name='картинка'
    )

    is_access = models.BooleanField(
        default=True,
        verbose_name='Доступ'
    )

    date_created = models.DateTimeField(
        auto_now_add=True
    )




    @property
    def date(self):
        return self.date_created.strftime('%H:%M %d %m %Y')


    def __str__(self):
        return f'Книга: {self.title} | Автор: {self.author.name}'

    class Meta:
        verbose_name = 'книга'
        verbose_name_plural = 'книги'

class Basket(models.Model):
    user = models.ForeignKey(to='users.User', on_delete=models.CASCADE)
    book = models.ForeignKey(to='Book', on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата получения/сдачи')
    is_return = models.BooleanField(default=False, verbose_name='Возвращена')

    def __str__(self):
        return f'Книга для {self.user.first_name} {self.user.last_name} | Книга: {self.book}'

    @classmethod
    def create_or_update(cls, user, book_id):
        baskets = Basket.objects.filter(user=user, book_id=book_id)
        book = Book.objects.filter(id=book_id).first()

        if not baskets.exists() or baskets.latest().is_return:
            obj = Basket.objects.create(user=user, book_id=book_id, quantity=1, is_return=False)
            book.quantity -= 1
            book.is_access = bool(book.quantity)
            book.save()
            is_created = True

            return obj, is_created
        else:
            basket = baskets.latest()
            basket.is_return = False
            basket.quantity += 1
            book.quantity -= 1
            book.is_access = bool(book.quantity)
            book.save()
            basket.save()
            is_created = False

            return is_created, basket

    class Meta:
        get_latest_by = 'created_timestamp'
        verbose_name = 'книги на выдаче'
        verbose_name_plural = 'книги на выдаче'

main/library/views.py
from django.views.generic import TemplateView, ListView
from django.contrib.auth.decorators import login_required
from .models import Author, Book, Basket
from django.shortcuts import HttpResponseRedirect
from django.utils.timezone import now


class IndexView(TemplateView):
    template_name = 'library/index.html'
    name = 'Library'


class BookListView(ListView):
    model = Book
    template_name = 'library/products.html'
    paginate_by = 3
    title = 'Libray - Каталог'


    def get_queryset(self, author_id=None):
        queryset = super(BookListView, self).get_queryset()
        author_id = self.kwargs.get('author_id')
        return queryset.filter(author_id=author_id) if author_id else queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(BookListView, self).get_context_data()
        context['authors'] = Author.objects.all()
        return context



@login_required
def basket_add(request, book_id):
    Basket.create_or_update(user=request.user, book_id=book_id)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    book = Book.objects.get(id=basket.book.id)
    book.quantity += basket.quantity
    book.is_access = True
    basket.is_return = True
    basket.created_timestamp = now()
    book.save()
    basket.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

main/library/templates/library/components/footer.html
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Library Levkovich 2024</p>
    </div>
    <!-- /.container -->
</footer>

main/library/templates/library/components/index_content.html
<section>
    <!--    <div class="alert alert-light text-center" role="alert">-->
    <!--        Информационное сообщение-->
    <!--    </div>-->
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">Library</h1>
                <p>
                    Открой двери к бесконечному миру знаний, где каждая страница книги - ключ к новым открытиям и вдохновению!
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'books:catalog' %}">
                        Начать читать!
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>

main/library/templates/library/components/menu.html
<div class="col-lg-3">

  <h1 class="my-4">Library</h1>
  <div class="list-group">
    {% for author in authors %}
      <a href="{% url 'books:author' author.id %}" class="list-group-item">{{ author.name }}</a>
    {% endfor %}
  </div>

</div>

main/library/templates/library/components/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'books:index' %}">Library</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'books:catalog' %}">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>

                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user-circle"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href="{% url 'users:profile' user.id %}">Профиль</a>
                        </li>
                        {% if user.is_superuser %}
                        <li><a class="dropdown-item" href="{% url 'admin:index' %}">Админ-панель</a></li>
                        {% endif %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'users:logout' %}">
                                Выйти
                            </a>
                        </li>
                    </ul>
                </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

main/library/templates/library/components/paginator.html
                {% if is_paginated %}
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center">
                            <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                                <a class="page-link"
                                   href="{% if page_obj.has_previous %} {% url 'books:paginator' page_obj.previous_page_number %} {% else %} # {% endif %}"
                                   tabindex="-1" aria-disabled="true">
                                    Предыдущая
                                </a>
                            </li>
                            {% for page in paginator.page_range %}
                                <li class="page-item">
                                    <a class="page-link" href="{% url 'books:paginator' page %}">
                                        {{ page }}
                                    </a>
                                </li>
                            {% endfor %}
                            <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                                <a class="page-link"
                                   href="{% if page_obj.has_next %} {% url 'books:paginator' page_obj.next_page_number %} {% else %} # {% endif %}">
                                    Следующая
                                </a>
                            </li>
                        </ul>
                    </nav>

                {% endif %}

main/library/templates/library/components/product_card.html
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#">
                            <img class="card-img-top"
                                 src="{{ book.image.url }}"
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h5 class="card-title">
                                <a href="#">{{ book.title }}</a>
                            </h5>
                            <h5>{{ book.author }}</h5>
                        </div>
                        <div class="card-footer text-center">
                            <a class="btn btn-outline-success" href="{% url 'books:basket_add' book.id %}">
                                Заказать
                            </a>
                        </div>
                    </div>
                </div>

main/library/templates/library/components/products_content.html
<div class="container">
    <div class="row">
            {% include 'library/components/menu.html' %}
        <!-- /.col-lg-3 -->
        <div class="col-lg-7">
            {% include 'library/components/slider.html' %}
                <div class="row">
                    {% for book in object_list %}
                        {% if book.is_access %}
                            {% include 'library/components/product_card.html' %}
                        {% endif %}
                    {% endfor %}
                </div>
            {% include 'library/components/paginator.html' %}
        </div>
    </div>
</div>

main/library/templates/library/components/slider.html
{% load static %}

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>